name: Test

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGUSER: defund-police_service
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: defund-police_service
          POSTGRES_DB: defund-police_service_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Dependencies
    - name: Install missing libs (This is slated to be added to the base image soon!)
      run: sudo apt-get -yqq install libpq-dev
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
    - name: Ruby gem cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: v1-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          v1-${{ runner.os }}-gems-
    - name: Install gems
      run: |
        gem install bundler -v $(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -1 | tr -d " ")
        bundle config path vendor/bundle
        bundle config --local build.sassc --disable-march-tune-native # https://github.com/sass/sassc-ruby/issues/146
        bundle install --jobs 4 --retry 3 --frozen && bundle clean
    # /Dependencies

    - name: Setup test database
      run: bundle exec rake db:test:prepare
    - name: Compile assets
      run: bundle exec rake assets:precompile
    - name: Run tests
      run: RAILS_ENV=test DISABLE_SPRING=1 bundle exec rspec
